# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
asd = np.zeros(shape=10)

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
asd.size

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [14]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
newone = np.zeros(shape=10)
newone[4] =1
print(newone)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [19]:
vectorN = np.arange(10, 49)
vectorN

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [21]:
reversedV = vectorN[::-1]
reversedV

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [23]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [36]:
listN =[1,2,0,0,4,0]
asd = [i  for i,n   in enumerate(listN) if n!=0 ]
print(asd)

[0, 1, 4]


In [35]:

my_list = [1, 2, 0, 0, 4, 0]
arr = np.array(my_list)
non_zero_indices = np.nonzero(arr)[0]
print(non_zero_indices)

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [38]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [50]:
s = np.random.random((3,3,3))
s

array([[[0.61459463, 0.35373931, 0.64291842],
        [0.70992528, 0.004343  , 0.6869509 ],
        [0.61737506, 0.87043024, 0.36855743]],

       [[0.54286357, 0.47348358, 0.3935914 ],
        [0.07230424, 0.78117739, 0.0027318 ],
        [0.51309419, 0.88737008, 0.1077534 ]],

       [[0.06879406, 0.54368199, 0.16252163],
        [0.17888497, 0.76586881, 0.07990085],
        [0.154958  , 0.7602389 , 0.86956363]]])

In [54]:
random_1dmatrix = np.random.rand(3,3)
print(random_1dmatrix)

[[0.85276517 0.13708325 0.71760866]
 [0.31964374 0.21041168 0.81178603]
 [0.51326735 0.24210422 0.55414248]]


In [56]:
random_number = np.random.rand()
print(random_number)

0.28153154286895


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [62]:
z = np.random.rand(10,10)
Zmin = z.min()
Zmax = z.max()
print(Zmin, Zmax)

0.013664345359020058 0.9516449247080947


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [66]:
z = np.random.rand(30)
zMean = z.mean()
zMean

0.45322159027962977

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [72]:
zs = np.ones((10,10))
zs[1:-1, 1:-1] = 0
zs

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [76]:
sz = np.zeros((5,5))
sz[[0, -1], :] = 1 #- modify the first and last rows and all the columns from these
sz[:,[0, -1]] = 1 #modify all the rows from the column 1 and -1
sz

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [5]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [9]:
ZS = np.ones((5,5))

ZS[:, [0, -1]] = 0
ZS[[0, -1], :] = 0
ZS

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [13]:
# print(0 * np.nan)
# print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

In [17]:
Z = np.diag(np.arange(4), k=-1)
Z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [23]:
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [27]:
origArr = np.array([[0, 1], [1, 0]])


print(np.tile(origArr, (4, 4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

- normalization is fitting the data in a range between [0,1] or [-1,1]
- formula is 
X_normalized = (X - X_min) / (X_max - X_min)

- z-score standardization:
 Z = (X - μ) / σ    
    Z is the standardized value.
    X is the original data point.
    μ is the mean of the data.
    σ is the standard deviation of the data.

Uses:
1. Comparability - makes features comparable since they are all at the same scale
2. stability 
3. Convergence - ML algorithms converge faster when the input features are normalized, helps prevent one feature from dominating the process
4. Interpretability - reduces the influence of the scale of the data on the model coeficients
5. Visualization - 


In [31]:
matrx = np.random.random((5, 5))
min_val = np.min(matrx)
max_val = np.max(matrx)
normalized_matrx =( matrx - min_val) /( max_val - min_val)
print(normalized_matrx)


#Z score standardization:
meanM = np.mean(matrx)
stdM = np.std(matrx)

zNormalized = (matrx - meanM)/ stdM
print(zNormalized)


[[0.95303354 0.76951655 0.72164917 0.76379162 0.33376644]
 [0.42308452 0.86485719 1.         0.96639828 0.10053584]
 [0.06991001 0.         0.7220189  0.14620158 0.60064177]
 [0.82107783 0.12233999 0.62992033 0.72167652 0.22836336]
 [0.66298493 0.29879063 0.77848699 0.25783557 0.83820955]]
[[ 1.28272902  0.69602656  0.54299488  0.67772399 -0.69706334]
 [-0.41151408  1.00082988  1.43288045  1.325456   -1.44269984]
 [-1.54061041 -1.76411218  0.54417693 -1.29670681  0.15613513]
 [ 0.86086758 -1.37299215  0.24973847  0.54308234 -1.0340362 ]
 [ 0.35544576 -0.80888073  0.72470497 -0.93981378  0.91563758]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color =np.dtype(
    [
        ("r", np.ubyte),
        ("g", np.ubyte),
        ("b", np.ubyte),
        ("a", np.ubyte),
    ]
)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [35]:
aM = np.random.random((5, 3))
bM = np.random.random((3, 2))
prodC = np.dot(aM, bM)
prodCA = aM @ bM
print(prodC, prodCA)

[[0.60904931 1.08920696]
 [0.27263391 1.14515554]
 [0.08726294 0.25282027]
 [0.51159639 1.44959039]
 [0.67221886 1.22587896]] [[0.60904931 1.08920696]
 [0.27263391 1.14515554]
 [0.08726294 0.25282027]
 [0.51159639 1.44959039]
 [0.67221886 1.22587896]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [46]:
arrD = np.random.randint(1, 11, size=(1,10))
arrD[(arrD>=3) & (arrD<=8)] *= -1
print(arrD) 


[[-5  1  1 -6  1 -5 -6 -4 -8 -4]]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [56]:
print(sum(np.array(range(5)), -1))
from numpy import *
print(sum(range(5), -1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [59]:
Z = np.random.randint(1,11, size=(3,3))
Z**Z

array([[     46656,          4,          1],
       [  16777216,          1,  387420489],
       [1410065408,        256,     823543]])

In [71]:
# print(Z>>2)
# print(Z<-Z)
# print(1j*Z)
print(Z/1/1)

print(Z)


[[ 6.  2.  1.]
 [ 8.  1.  9.]
 [10.  4.  7.]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [74]:
print(np.array(0)/np.array(0))

nan


C:\Users\V3790422\AppData\Local\Temp\ipykernel_20336\274812390.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0))


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

numpy.where(condition, [x, y])

-> where the condition is true yield X otherwise yield Y

In [75]:
Z = np.random.uniform(-10, 10, 10)
Z

array([-0.37294928,  9.23707446,  6.52612016, -9.66099547, -6.225511  ,
        5.97607351,  9.76687603,  4.97626874, -4.47723139, -6.00208167])

In [77]:
print(np.where(Z >=0, np.ceil(Z), np.floor(Z)))

[ -1.  10.   7. -10.  -7.   6.  10.   5.  -5.  -7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [79]:
Z = np.random.randint(0,10,size=(5,5))
S = np.random.randint(0,10,size=(5,5))
print(Z)
print(S)
print(np.intersect1d(Z, S))


[[6 6 6 2 7]
 [5 9 7 2 6]
 [8 7 2 4 4]
 [6 8 2 3 7]
 [9 8 4 1 5]]
[[7 7 9 5 2]
 [3 1 9 0 9]
 [3 0 7 9 7]
 [4 8 4 2 6]
 [5 9 8 0 9]]
[1 2 3 4 5 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [83]:
print(np.sqrt(1) == np.emath.sqrt(1))

True


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [94]:
yesterday = np.datetime64('now') - np.timedelta64(1, "h")

print(yesterday)

2023-09-14T12:45:15


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [101]:
A = np.ones(3)
B = np.ones(3)*2
print(A)
print(B)
asd = np.divide(A, 2)
print(asd)
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A,B, out=A)


[1. 1. 1.]
[2. 2. 2.]
[0.5 0.5 0.5]


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [111]:
origArr = np.random.uniform(0,10, 10)
print(origArr)
integrArr = np.floor(origArr)
print(integrArr)
intr =origArr.astype(int)
print(intr)
intr2 =np.trunc(origArr)
print(intr2)
integrArr2 = np.floor(origArr)
print(integrArr2)
print(origArr//1)
print(origArr - origArr%1)


[7.24166724 8.6262069  8.23511269 2.24047287 8.01033341 0.21546507
 3.85033637 3.39570396 5.47257373 9.23504517]
[7. 8. 8. 2. 8. 0. 3. 3. 5. 9.]
[7 8 8 2 8 0 3 3 5 9]
[7. 8. 8. 2. 8. 0. 3. 3. 5. 9.]
[7. 8. 8. 2. 8. 0. 3. 3. 5. 9.]
[7. 8. 8. 2. 8. 0. 3. 3. 5. 9.]
[7. 8. 8. 2. 8. 0. 3. 3. 5. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [116]:
# Z = np.zeros((5,5))
Z=np.arange(5)
print(Z)

[0 1 2 3 4]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [119]:
def generate_integers(n):
    for i in range(n):
        yield i
generator = generate_integers(6)
npArr = np.array(list(generator))
print(npArr)


[0 1 2 3 4 5]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

- np.linspace() - used to generate a sequence of evenly spaced numbers over a specified range
-> used for generating a set of values linearly spaced between start and end with a specified number oif elements 
np.linspace( start, stop, num=40, endpoint=True, restep=False, dtype=None, axis=0)

In [121]:
arr = np.linspace(0, 1, num=10, endpoint=False )
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [128]:
vectRand =np.linspace(0, 1, num=10, endpoint=False )
vectRand.sort()
print(vectRand)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [133]:
arrS = np.add(vectRand, vectRand)
arrS = arrS.reduce()
print(arrS)

AttributeError: 'numpy.ndarray' object has no attribute 'reduce'

#### 42. Consider two random array A and B, check if they are equal (★★☆)

- np.all() - verify if all elements form an array evaluate to true

In [145]:
array1 = np.array([1, 2, 3])
array2 = np.array([1, 2, 3, 4])
# are_equal = (array1 == array2).all()
print(array1 == array2)

False


C:\Users\V3790422\AppData\Local\Temp\ipykernel_20336\824112778.py:4: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(array1 == array2)


In [146]:
np.array([-1, 2, 3]).all()


True

In [147]:
np.array([0, 2, 3]).all()

False

#### 43. Make an array immutable (read-only) (★★☆)

In [152]:
wArr = np.random.randint(1, 10, size=(3,3))
wArr.flags.writeable = False

if wArr.flags.writeable:
    print("Array is writable")
else:
    print("Array is read-only")

Array is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [2]:
import numpy as np

In [6]:
randV = np.random.rand(10)
print(randV)

max_idx = randV.argmax()
print(max_idx)

randV[max_idx] = 0
print(randV)



[0.85543429 0.92090065 0.30369538 0.19705208 0.65336799 0.84171571
 0.76685409 0.78076119 0.58308453 0.21123342]
1
[0.85543429 0.         0.30369538 0.19705208 0.65336799 0.84171571
 0.76685409 0.78076119 0.58308453 0.21123342]


### Mail Exercises

In Python, whether a modification to a list is done in-place (modifying the original list) or not (creating a new list with the modification) depends on the specific operation you perform on the list. Here are some common operations and their behavior:

**Modifying a List in Place:**
1. **Using List Methods:** Most list methods, such as `append()`, `extend()`, `insert()`, `remove()`, and `pop()`, modify the list in place.

   Example:
   ```python
   my_list = [1, 2, 3]
   my_list.append(4)  # Modifies my_list in place by adding 4 to the end
   ```

2. **Slicing with Assignment:** You can modify a specific portion of a list in place by using slicing and assignment.

   Example:
   ```python
   my_list = [1, 2, 3, 4, 5]
   my_list[1:3] = [7, 8]  # Modifies my_list in place by replacing elements 2 and 3
   ```

**Creating a New List:**
1. **Concatenation:** When you concatenate two lists using the `+` operator, a new list is created with the concatenated elements.

   Example:
   ```python
   list1 = [1, 2, 3]
   list2 = [4, 5, 6]
   new_list = list1 + list2  # Creates a new list with elements from both lists
   ```

2. **List Comprehensions:** List comprehensions can be used to create a new list based on an existing list.

   Example:
   ```python
   original_list = [1, 2, 3]
   new_list = [x * 2 for x in original_list]  # Creates a new list with doubled values
   ```

3. **Using Functions:** Some functions that operate on lists, like `sorted()`, `reversed()`, and `filter()`, return a new list, leaving the original list unchanged.

   Example:
   ```python
   original_list = [3, 1, 2]
   sorted_list = sorted(original_list)  # Creates a new sorted list
   ```

4. **Slicing:** Slicing without assignment creates a new list containing the specified portion of the original list.

   Example:
   ```python
   original_list = [1, 2, 3, 4, 5]
   sliced_list = original_list[1:4]  # Creates a new list with elements 2, 3, 4
   ```

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)