In [28]:
# Fa o lista cu numere de la 1 la 7  (tip A)
listA= []
for i in range(1,8):
    listA.append(i)

print(listA)


[1, 2, 3, 4, 5, 6, 7]


In [29]:
#Fa o alta lista, ce contine liste cu numere de la 1 la 7. Sa contina 5 astfel de liste. Si la fiecare lista, adaugi 10 * indexul listei. De ex. prima lista e [1, 2, ... 7], a doua lista din aceata lista mai mare, e [11, 12, ...  17], a treia e [21, 22, ...27]  (ii zicem tip B)
listB=[]

for i in range(5):
    inner_list = []
    print(listB)
    for x in range(1,8):
        inner_list.append(i*10 +x)
    listB.append(inner_list) 
 

print(listB)

[]
[[1, 2, 3, 4, 5, 6, 7]]
[[1, 2, 3, 4, 5, 6, 7], [11, 12, 13, 14, 15, 16, 17]]
[[1, 2, 3, 4, 5, 6, 7], [11, 12, 13, 14, 15, 16, 17], [21, 22, 23, 24, 25, 26, 27]]
[[1, 2, 3, 4, 5, 6, 7], [11, 12, 13, 14, 15, 16, 17], [21, 22, 23, 24, 25, 26, 27], [31, 32, 33, 34, 35, 36, 37]]
[[1, 2, 3, 4, 5, 6, 7], [11, 12, 13, 14, 15, 16, 17], [21, 22, 23, 24, 25, 26, 27], [31, 32, 33, 34, 35, 36, 37], [41, 42, 43, 44, 45, 46, 47]]


In [30]:
#Fa inca o lista, ce contine mai multe liste de liste de tip B. 3 astfel de liste Dar la fiecare astfel de lista de tip B, adaugi 100*index. Astfel, prima lista de tip B incepe tot cu 1,2   dar a 2-a lista incepe cu 101 102 etc.
listC=[]

for j in range(3):
    listCB = []
    for i in range(5):
        listCA = []
        for x in range(1,8):
            listCA.append(j*100 +10*i + x)

        listCB.append(listCA)
    listC.append(listCB)

print(listC)

[[[1, 2, 3, 4, 5, 6, 7], [11, 12, 13, 14, 15, 16, 17], [21, 22, 23, 24, 25, 26, 27], [31, 32, 33, 34, 35, 36, 37], [41, 42, 43, 44, 45, 46, 47]], [[101, 102, 103, 104, 105, 106, 107], [111, 112, 113, 114, 115, 116, 117], [121, 122, 123, 124, 125, 126, 127], [131, 132, 133, 134, 135, 136, 137], [141, 142, 143, 144, 145, 146, 147]], [[201, 202, 203, 204, 205, 206, 207], [211, 212, 213, 214, 215, 216, 217], [221, 222, 223, 224, 225, 226, 227], [231, 232, 233, 234, 235, 236, 237], [241, 242, 243, 244, 245, 246, 247]]]


In [31]:
# Din lista aia de liste de liste, faci un array numpy. 
ndArr = np.array(listC)
print(ndArr)



[[[  1   2   3   4   5   6   7]
  [ 11  12  13  14  15  16  17]
  [ 21  22  23  24  25  26  27]
  [ 31  32  33  34  35  36  37]
  [ 41  42  43  44  45  46  47]]

 [[101 102 103 104 105 106 107]
  [111 112 113 114 115 116 117]
  [121 122 123 124 125 126 127]
  [131 132 133 134 135 136 137]
  [141 142 143 144 145 146 147]]

 [[201 202 203 204 205 206 207]
  [211 212 213 214 215 216 217]
  [221 222 223 224 225 226 227]
  [231 232 233 234 235 236 237]
  [241 242 243 244 245 246 247]]]


In [32]:
#Cum arata daca selectezi, pe verticala, toate celulele de coordonate (rand 2, coloana 3), pe verticala, din toate foile?
coord23 = ndArr[:, 2, 3]

# Print the selected cells
print(coord23)

coord4 = ndArr[:, :, 4]
print(coord4)




[ 24 124 224]
[[  5  15  25  35  45]
 [105 115 125 135 145]
 [205 215 225 235 245]]


In [33]:
import numpy as np

In [34]:
#Create a 4x4 identity matrix using NumPy.
idM = np.eye(4,4)
print(idM)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
#Create a NumPy array containing the numbers from 1 to 20. Reshape it into a 4x5 matrix.
arr = np.random.randint(1,20, (1, 20))
arr = np.reshape(arr,(4,5))
print(arr)


[[10 12  9 10  2]
 [19 16 14  8 12]
 [ 4 17 18  7  2]
 [ 5 14  3  1 11]]


In [36]:
# transpose an array You can transpose a NumPy array using the .T attribute or the numpy.transpose() function. Here's how you can transpose your array arr:


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(arr.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [37]:
#MAtrix multiplication

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = np.dot(arr1, arr2)

In [38]:
#Create a NumPy array containing the numbers from 0 to 9. Extract all even numbers from the array.
randArr = np.random.randint(0,9, (1,10))
print(randArr)
evenNr = randArr[randArr%2 ==0]
print(evenNr)


[[4 3 1 2 0 8 1 5 7 0]]
[4 2 0 8 0]


In [39]:
#Create a 3x3 NumPy array containing random integers between 1 and 10. Replace all values greater than 5 with the value 5.

arrO = np.random.randint(1,11, (3,3))
print(arrO)
arrO[arrO > 5 ] = 5
print(arrO)




[[ 7  1  4]
 [10  9 10]
 [ 9  7  8]]
[[5 1 4]
 [5 5 5]
 [5 5 5]]


In [40]:
#Create a 5x5 NumPy array with random values. Calculate the mean, median, and standard deviation of the values in the array.
arr = np.random.randint(1, 20, (5,5))
meanA = arr.mean()
stdA = arr.std()
mediaN = np.median(arr)

print(arr)
print(meanA)
print(stdA)
print(mediaN)


[[12  7  5 14 18]
 [ 7  4  1  4  8]
 [19  2 18  8  3]
 [ 5  7 14  4  8]
 [ 6 10 15 14  4]]
8.68
5.236181815025144
7.0


In [41]:
#Create a 6x6 NumPy array of zeros. Replace the middle 4x4 region with ones.
array = np.zeros((6, 6), dtype=int)
print(array)
# Replace the middle region with ones
array[1:5, 1:5] = 1

# Print the resulting array
print(array)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


In [42]:
#Create a 4x4 NumPy array with random values. Find the indices (row and column) of the maximum value in the array.

arr = np.random.rand(4,4)
max_index = np.unravel_index(np.argmax(arr), arr.shape)

print(arr)
print(max_index)




[[0.94256491 0.68296104 0.47768265 0.88475076]
 [0.58373623 0.61399081 0.59563197 0.36499676]
 [0.61225331 0.53963513 0.9415131  0.72824002]
 [0.35797728 0.86618035 0.38874472 0.16971183]]
(0, 0)


In [43]:
import pandas as pd

In [44]:

s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['c', 'd', 'e', 'f'])

# Try to write code that will add the 2 previous series together,
# but treating missing values from either series as 0. The result
# when printed out should be similar to the following line:
# print pd.Series([1, 2, 13, 24, 30, 40], index=['a', 'b', 'c', 'd', 'e', 'f'])

print( s1.add(s2, fill_value=0))

a     1.0
b     2.0
c    13.0
d    24.0
e    30.0
f    40.0
dtype: float64
