In [2]:
import pandas as pd
import numpy as np

In [53]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [4, 5, 6],
    [7, 8, 9],
    [7, 8, 9]
])

print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))


84
[23 28 33]
[ 6 15 15 24 24]


In [60]:
ridership = np.array([
   [ 5, 10, 15, 20, 25], [ 5, 10, 15, 20, 25], [ 5, 10, 15, 20, 25]
])
ridership


array([[ 5, 10, 15, 20, 25],
       [ 5, 10, 15, 20, 25],
       [ 5, 10, 15, 20, 25]])

In [63]:

def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. That is, find the maximum
    mean-ridership-per-day and the minimum mean-ridership-per-day for any
    subway station.
    '''
    mean_per_day = np.mean(ridership, axis = 0)
    print(mean_per_day)


    max_daily_ridership = np.max(mean_per_day)   # Replace this with your code
    min_daily_ridership =  np.min(mean_per_day)     # Replace this with your code

    
    return (max_daily_ridership, min_daily_ridership)

min_and_max_riders_per_day([[ 5, 10, 15, 20, 25], [ 5, 10, 15, 20, 25], [ 5, 10, 15, 20, 25]])

[ 5. 10. 15. 20. 25.]


(25.0, 5.0)

In [40]:

# print(ridership[1, 3])
# print(ridership[1:3, 3:5])
# print(ridership[0, :])
print( ridership[:, 1])
# print(ridership[0, :] + ridership[1, :])
print(ridership[:, 0] )

print(ridership[:, 0] + ridership[:, 1])


[   0 3877 4088 3392 4802 3933  229    0 3785 4043]
[   0 1478 1613 1560 1608 1576   95    2 1438 1342]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [41]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print (a + b)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [3]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    overall_mean = None # Replace this with your code
    mean_for_max = None # Replace this with your code
    
    return (overall_mean, mean_for_max)

Date of Transaction Branch Name  Amount of Sales  Is Active
0           January 1    Branch A            500.0       True
1           January 2    Branch B            600.0      False

In [5]:
df_primary = pd.concat([df_primary, df_default_data])

df_primary

Date of Transaction Branch Name  Amount of Sales  Is Active
0           January 5    Branch C            100.0       True
1           January 6    Branch B            200.0       True
0           January 1    Branch A            500.0       True
1           January 2    Branch B            600.0      False

In [6]:
df_primary.reset_index(drop=True, inplace=True)

In [7]:
df_primary

Date of Transaction Branch Name  Amount of Sales  Is Active
0           January 5    Branch C            100.0       True
1           January 6    Branch B            200.0       True
2           January 1    Branch A            500.0       True
3           January 2    Branch B            600.0      False

In [64]:
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

In [66]:
ridership_df

R003  R004  R005  R006  R007
05-01-11     0     0     2     5     0
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
05-05-11  1608  4802  3932  4477  2705
05-06-11  1576  3933  3909  4979  2685
05-07-11    95   229   255   496   201
05-08-11     2     0     1    27     0
05-09-11  1438  3785  3589  4174  2215
05-10-11  1342  4043  4009  4665  3033

In [65]:
df_1 = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
print(df_1)

# You can also use a list of lists or a 2D NumPy array
df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns=['A', 'B', 'C'])
print(df_2)

   A  B
0  0  3
1  1  4
2  2  5
   A  B  C
0  0  1  2
1  3  4  5


In [79]:
# print(ridership_df.iloc[0])
# print(ridership_df.loc['05-05-11'])
# print(ridership_df['R003'])
# print(ridership_df.iloc[1, 3])
# print(ridership_df['R003', 'R005'])
print(ridership_df[['R003', 'R005']])

          R003  R005
05-01-11     0     2
05-02-11  1478  3674
05-03-11  1613  3991
05-04-11  1560  3826
05-05-11  1608  3932
05-06-11  1576  3909
05-07-11    95   255
05-08-11     2     1
05-09-11  1438  3589
05-10-11  1342  4009


In [81]:
df = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
df

A  B
0  0  3
1  1  4
2  2  5

In [90]:
# df.sum(axis=1)
# df.sum()
print(df.sum(axis=0))
print(df.sum(axis=1))

A     3
B    12
dtype: int64
0    3
1    5
2    7
dtype: int64


In [89]:
df.values.sum()


15

In [94]:
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)
ridership_df

R003  R004  R005  R006  R007
05-01-11     0     0     2     5     0
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
05-05-11  1608  4802  3932  4477  2705
05-06-11  1576  3933  3909  4979  2685
05-07-11    95   229   255   496   201
05-08-11     2     0     1    27     0
05-09-11  1438  3785  3589  4174  2215
05-10-11  1342  4043  4009  4665  3033

In [112]:
ridership = pd.DataFrame( {0: [5, 5, 5], 1: [10, 10, 10], 2: [15, 15, 15], 3: [20, 20, 20], 4: [25, 25, 25]}, index=[0, 1, 2] )

In [113]:
def mean_riders_for_max_station(ridership_df):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    This is the same as a previous exercise, but this time the
    input is a Pandas DataFrame rather than a 2D NumPy array.
    '''
    max_riders = ridership_df.iloc[0].idxmax()
    # print(max_riders)
    overall_mean = ridership_df.mean().mean() # Replace this with your code
    mean_for_max = ridership_df[max_riders].mean() # Replace this with your code
    
    return (overall_mean, mean_for_max)

print(mean_riders_for_max_station(ridership))

(15.0, 25.0)


In [7]:
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]})
print(f'DF1 : {df1}')
print(f'DF2 : {df2}')
print(df1 + df2)


DF1 :    a  b  c
0  1  4  7
1  2  5  8
2  3  6  9
DF2 :     a   b   c
0  10  40  70
1  20  50  80
2  30  60  90
    a   b   c
0  11  44  77
1  22  55  88
2  33  66  99


    a   b   c
0  11  44  77
1  22  55  88
2  33  66  99


In [10]:
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({                'b': [40, 50, 60], 'c': [70, 80, 90], 'd': [10, 20, 30], })
print(df1 + df2)

    a   b   c   d
0 NaN  44  77 NaN
1 NaN  55  88 NaN
2 NaN  66  99 NaN


In [12]:
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]},
                    index=['row1', 'row2', 'row3'])
df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]},
                    index=['row4', 'row3', 'row2'])
print(f'DF1: {df1}')
print(f'DF2: {df2}')
print(df1 + df2)

DF1:       a  b  c
row1  1  4  7
row2  2  5  8
row3  3  6  9
DF2:        a   b   c
row4  10  40  70
row3  20  50  80
row2  30  60  90
         a     b     c
row1   NaN   NaN   NaN
row2  32.0  65.0  98.0
row3  23.0  56.0  89.0
row4   NaN   NaN   NaN


In [14]:
entries_and_exits = pd.DataFrame({
    'ENTRIESn': [3144312, 3144335, 3144353, 3144424, 3144594,
                 3144808, 3144895, 3144905, 3144941, 3145094],
    'EXITSn': [1088151, 1088159, 1088177, 1088231, 1088275,
               1088317, 1088328, 1088331, 1088420, 1088753]
})
entries_and_exits


ENTRIESn   EXITSn
0   3144312  1088151
1   3144335  1088159
2   3144353  1088177
3   3144424  1088231
4   3144594  1088275
5   3144808  1088317
6   3144895  1088328
7   3144905  1088331
8   3144941  1088420
9   3145094  1088753

In [18]:
diff_df = entries_and_exits.diff().fillna(0)
diff_df.columns = ['Hourly Entries', 'Hourly Exits']

In [19]:
diff_df

ENTRIESn  EXITSn
0       0.0     0.0
1      23.0     8.0
2      18.0    18.0
3      71.0    54.0
4     170.0    44.0
5     214.0    42.0
6      87.0    11.0
7      10.0     3.0
8      36.0    89.0
9     153.0   333.0

In [20]:
def get_hourly_entries_and_exits(entries_and_exits):
    '''
    Fill in this function to take a DataFrame with cumulative entries
    and exits (entries in the first column, exits in the second) and
    return a DataFrame with hourly entries and exits (entries in the
    first column, exits in the second).
        '''
    hourly_df = entries_and_exits.diff().fillna(0)

    hourly_df.columns = ['Hourly Entries', 'Hourly Exits']


    return hourly_df
get_hourly_entries_and_exits(entries_and_exits)

Hourly Entries  Hourly Exits
0             0.0           0.0
1            23.0           8.0
2            18.0          18.0
3            71.0          54.0
4           170.0          44.0
5           214.0          42.0
6            87.0          11.0
7            10.0           3.0
8            36.0          89.0
9           153.0         333.0

In [24]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)
grades_df

exam1  exam2
Andre       43     24
Barry       81     63
Chris       78     56
Dan         75     56
Emilio      89     67
Fred        70     51
Greta       91     79
Humbert     65     46
Ivan        98     72
James       87     60

In [34]:
def convert_grades(grades):
    '''
    Fill in this function to convert the given DataFrame of numerical
    grades to letter grades. Return a new DataFrame with the converted
    grade.
    
    The conversion rule is:
        90-100 -> A
        80-89  -> B
        70-79  -> C
        60-69  -> D
        0-59   -> F
    '''
 
    grade_mapping = {
        'A': range(90, 101),
        'B': range(80, 90),
        'C': range(70, 80),
        'D': range(60, 70),
        'F': range(0, 60)
    }


    letter_grades = grades.applymap(lambda grade:next((letter for letter, range in grade_mapping.items() if grade in range), None))

    return letter_grades

convert_grades(grades_df)

C:\Users\V3790422\AppData\Local\Temp\ipykernel_6128\912668043.py:24: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  letter_grades = grades.applymap(lambda grade:next((letter for letter, range in grade_mapping.items() if grade in range), None))


exam1 exam2
Andre       F     F
Barry       B     D
Chris       C     F
Dan         C     F
Emilio      B     D
Fred        C     F
Greta       A     C
Humbert     D     F
Ivan        A     C
James       B     D

In [35]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)

# Change False to True for this block of code to see what it does

# DataFrame apply()
def convert_grades_curve(exam_grades):
    # Pandas has a bult-in function that will perform this calculation
    # This will give the bottom 0% to 10% of students the grade 'F',
    # 10% to 20% the grade 'D', and so on. You can read more about
    # the qcut() function here:
    # http://pandas.pydata.org/pandas-docs/stable/generated/pandas.qcut.html
    return pd.qcut(exam_grades,
                    [0, 0.1, 0.2, 0.5, 0.8, 1],
                    labels=['F', 'D', 'C', 'B', 'A'])
    
# qcut() operates on a list, array, or Series. This is the
# result of running the function on a single column of the
# DataFrame.
print(convert_grades_curve(grades_df['exam1']))

# qcut() does not work on DataFrames, but we can use apply()
# to call the function on each column separately
print(grades_df.apply(convert_grades_curve))

Andre      F
Barry      B
Chris      C
Dan        C
Emilio     B
Fred       C
Greta      A
Humbert    D
Ivan       A
James      B
Name: exam1, dtype: category
Categories (5, object): ['F' < 'D' < 'C' < 'B' < 'A']
        exam1 exam2
Andre       F     F
Barry       B     B
Chris       C     C
Dan         C     C
Emilio      B     B
Fred        C     C
Greta       A     A
Humbert     D     D
Ivan        A     A
James       B     B


In [43]:
def standardize(df):
    '''
    Fill in this function to standardize each column of the given
    DataFrame. To standardize a variable, convert each value to the
    number of standard deviations it is above or below the mean.
    '''
    stds = df.std(ddof=0)
    means = df.mean()


    standardize = (df-means) / stds
    print(f'DDDDDD: {df-means}')
    # print(f'Mean: {means}')


    return standardize


standardize(grades_df)


DDDDDD:          exam1  exam2
Andre    -34.7  -33.4
Barry      3.3    5.6
Chris      0.3   -1.4
Dan       -2.7   -1.4
Emilio    11.3    9.6
Fred      -7.7   -6.4
Greta     13.3   21.6
Humbert  -12.7  -11.4
Ivan      20.3   14.6
James      9.3    2.6


exam1     exam2
Andre   -2.315341 -2.304599
Barry    0.220191  0.386400
Chris    0.020017 -0.096600
Dan     -0.180156 -0.096600
Emilio   0.753987  0.662400
Fred    -0.513779 -0.441600
Greta    0.887436  1.490400
Humbert -0.847401 -0.786600
Ivan     1.354508  1.007400
James    0.620538  0.179400

In [44]:
df = pd.DataFrame({
    'a': [4, 5, 3, 1, 2],
    'b': [20, 10, 40, 50, 30],
    'c': [25, 20, 5, 15, 10]
})

# Change False to True for this block of code to see what it does

# DataFrame apply() - use case 2
print(df.apply(np.mean))
print(df.apply(np.max))

a     3.0
b    30.0
c    15.0
dtype: float64
a     5
b    50
c    25
dtype: int64


In [48]:
def second_largest(df):
    '''
    Fill in this function to return the second-largest value of each 
    column of the input DataFrame.
    '''
    max = df.max()
    filtered_df = df[df != max]
    secondMax  = filtered_df.max()
    print(filtered_df)
    print(secondMax)


    return secondMax

second_largest(df)

     a     b     c
0  4.0  20.0   NaN
1  NaN  10.0  20.0
2  3.0  40.0   5.0
3  1.0   NaN  15.0
4  2.0  30.0  10.0
a     4.0
b    40.0
c    20.0
dtype: float64


In [49]:
def second_largest(df):
    '''
    Fill in this function to return the second-largest value of each 
    column of the input DataFrame.
    '''
    return df.apply(lambda column: column.nlargest(2).iloc[-1])

second_largest(df)

a     4
b    40
c    20
dtype: int64

In [50]:
# Adding a Series to a one-row DataFrame 
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    0: [10, 20, 30, 40],
    1: [50, 60, 70, 80],
    2: [90, 100, 110, 120],
    3: [130, 140, 150, 160]
})

print(df)
print(''  ) #Create a blank line between outputs
print(df + s)
    

    0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

    0   1    2    3
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


In [51]:

# Adding a Series to a one-column DataFram
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({0: [10], 1: [20], 2: [30], 3: [40]})

print(df)
print('') # Create a blank line between outputs
print(df + s)

    0   1   2   3
0  10  20  30  40

    0   1   2   3
0  11  22  33  44


In [53]:
# Adding when DataFrame column names match Series index
s = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
df = pd.DataFrame({
    'a': [10, 20, 30, 40],
    'b': [50, 60, 70, 80],
    'c': [90, 100, 110, 120],
    'd': [130, 140, 150, 160]
})
print(df)
print(s)
print('') # Create a blank line between outputs
print(df + s)

    a   b    c    d
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160
a    1
b    2
c    3
d    4
dtype: int64

    a   b    c    d
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


In [54]:
# Adding when DataFrame column names don't match Series index
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    'a': [10, 20, 30, 40],
    'b': [50, 60, 70, 80],
    'c': [90, 100, 110, 120],
    'd': [130, 140, 150, 160]
})
print(df)
print(s)
print('') # Create a blank line between outputs
print(df + s)

    a   b    c    d
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160
0    1
1    2
2    3
3    4
dtype: int64

    a   b   c   d   0   1   2   3
0 NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN


In [55]:
# Adding using +
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    0: [10, 20, 30, 40],
    1: [50, 60, 70, 80],
    2: [90, 100, 110, 120],
    3: [130, 140, 150, 160]
})
print(df)
print('') # Create a blank line between outputs
print(df + s)

    0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

    0   1    2    3
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


In [60]:
# Adding with axis='index'
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    0: [10, 20, 30, 40],
    1: [50, 60, 70, 80],
    2: [90, 100, 110, 120],
    3: [130, 140, 150, 160]
})

print(df)
print('') # Create a blank line between outputs
print(df.add(s, axis='index'))
# The functions sub(), mul(), and div() work similarly to add()


    0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

    0   1    2    3
0  11  51   91  131
1  22  62  102  142
2  33  73  113  153
3  44  84  124  164


In [61]:
# Adding with axis='columns'
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    0: [10, 20, 30, 40],
    1: [50, 60, 70, 80],
    2: [90, 100, 110, 120],
    3: [130, 140, 150, 160]
})

print(df)
print('') # Create a blank line between outputs
print(df.add(s, axis='columns'))
# The functions sub(), mul(), and div() work similarly to add()


    0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160

    0   1    2    3
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


In [ ]:

def standardize(df):
    '''
    Fill in this function to standardize each column of the given
    DataFrame. To standardize a variable, convert each value to the
    number of standard deviations it is above or below the mean.
    
    This time, try to use vectorized operations instead of apply().
    You should get the same results as you did before.
    '''
    return None